version: '2'
services: 
  
  flaskwebservice:
    build: 
      context: .
    ports:
      - 5000:5000
    volumes:
      - .:/usr/src/app

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.12.1
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
    volumes:
      - ./data:/home
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:
    driver: local      
    